---
version: "2.0"
services:
  service-1:
    image: karbivskyi/minebench-ui:v0.1.2.9
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
        accept:
          - "minebench.cloud"
profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
  placement:
    dcloud:
      pricing:
        service-1:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
          amount: 100000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
        allOf: []
deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1