version: "2.0"

services:
  minebench-ui:
    image: ghcr.io/YOUR_USERNAME/minebench-ui:latest
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    resources:
      cpu:
        units: 0.5
      memory:
        size: 512Mi
      storage:
        size: 1Gi

profiles:
  compute:
    minebench-ui:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1Gi
  placement:
    akash:
      pricing:
        minebench-ui:
          denom: uakt
          amount: 1000

deployment:
  minebench-ui:
    akash:
      profile: minebench-ui
      count: 1
