version: '3.8'

services:
  minebench-ui:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minebench.rule=Host(`minebench.local`)"
      - "traefik.http.services.minebench.loadbalancer.server.port=3000"
    networks:
      - minebench-network

networks:
  minebench-network:
    driver: bridge
